name = "BeamTracking"
uuid = "8ef5c10a-4ca3-437f-8af5-b84d8af36df0"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
AtomicAndPhysicalConstants = "5c0d271c-5419-4163-b387-496237733d8b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AtomicAndPhysicalConstants = "0.5.0"
Distributions = "0.25"
GTPSA = "1.2.0"
ReferenceFrameRotations = "3"
StaticArrays = "1"
StructArrays = "0.6.18, 0.7"
Unitful = "1.21.0"
julia = "1.9"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributions", "JET", "GTPSA", "BenchmarkTools"]
