name = "BeamTracking"
uuid = "8ef5c10a-4ca3-437f-8af5-b84d8af36df0"
authors = ["mattsignorelli <mgs255@cornell.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[weakdeps]
Beamlines = "5bb90b03-0719-46b8-8ce4-1ef3afd3cd4b"

[extensions]
BeamTrackingBeamlinesExt = "Beamlines"

[compat]
Beamlines = "0.1.0"
GTPSA = "1.4.1"
Polyester = "0.7.16"
ReferenceFrameRotations = "3"
SIMD = "3.7.1"
StaticArrays = "1"
VectorizationBase = "0.21.71"
julia = "1.9"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GTPSA = "b27dd330-f138-47c5-815b-40db9dd9b6e8"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributions", "JET", "GTPSA", "BenchmarkTools"]
